server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.5"
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.0"

  server:
    password: "happymusic"

    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true

  lavasrc:
    sources:
      spotify: true
      applemusic: true
      deezer: true
      yandexmusic: false

logging:
  level:
    root: INFO
