server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.5"

  server:
    password: "happymusic"

    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false

youtubePlugin:
  enabled: true
  allowSearch: true
  allowDirectVideoIds: true
  clients:
    - MUSIC
    - WEB

logging:
  level:
    root: INFO
